### ISSUE TITLE
Add Process view

### ISSUE THREAD

**Issue by hngskj** [hngskj/labnote#9]
We need the process view when the "Create Process" button is clicked.

The essential elements would be like:
- The name of a process (eg. Merge, Stir, Boil ...)
- The chemicals to be handled (drag-and-drop or click items in the list)
- The details of experimental conditions (eg. instruments, rpm, temperature ...)
- The expected result (the output chemical)

What else do we need?

**Comment by hngskj** [comment]
WIP
https://github.com/hngskj/labnote/blob/ds/src/data/sample_process.js

**Comment by jngynchoi** [comment]
In prototype, I think we don't need to include the expected result (the output chemical). That part seems to be a simulation area. Just creating the output chemical may be enough. (For example, when the user does washing process for AgNO3, labNote creates the output: AgNO3 after washing. The user check details of the output when he/she places the cursor on the output block.) 


In database spreadsheet, amount require means the process should include amount of input chemicals. (For example, add process needs 1. chemical A the user wants to add, 2.the amount of chemical A, 3. chemical B the user wants to add chemical A to, and 4. the amount of chemical B.)

Gradually means, when the user creates the process, the user can check gradually. Then the process needs time which the process continues.

**Comment by hngskj** [comment]
@jngynchoi 
Please add output information on [sample_process.js](https://github.com/hngskj/labnote/blob/ds/src/data/sample_process.js) file. (To-do number 4)
The output of the process is dependent on the method of process.

![200317](https://user-images.githubusercontent.com/16933598/76850987-d0bcd300-688b-11ea-8956-382ee36c9fe4.jpg)

**Comment by hngskj** [comment]
To select input(s) of the process, the button-like components will be provided.
Users will choose input by clicking them.
The input field will recognize its number of limitations.

**Comment by hngskj** [comment]
We don't need OUPUT field for the process view.

**Comment by hngskj** [comment]
Considering making Vue component for all types of processes

**Comment by hngskj** [comment]
Let me know the list of processes we will use shortly.
I will make process components first things first. :)
@jngynchoi

**Comment by hngskj** [comment]
Process components will live in `src/components/process`.
The naming convention will be `App[process_name].vue`.
e.g. `AppMix.vue`, `AppInject.vue`, `AppSonicate.vue`

**Comment by jngynchoi** [comment]
- Mix
- Stirring
- Heat
- Water bath
- Cooling
- Filtering

These are processes we need to make first.

**Comment by hngskj** [comment]
To-do
- [ ] Mix : aa308f5fc53bd3a05b12e2bae72be02da1aa3ab6
- [ ] Stirring
- [ ] Heat
- [ ] Water bath
- [ ] Cooling
- [ ] Filtering

**Comment by hngskj** [comment]
6 process views for existing data are done.

Since `Process.vue` is changed, creating a new process button needs to be fixed.

**Comment by hngskj** [comment]
Solve the above issue using the `process_template.js` file.
d5c70e3b868721928282b09ff4c230b50a60cfec
